version: '3.7'

services:
  haproxy:
    image: haproxy:alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:80"
    restart: unless-stopped
    networks:
      - rinha
    depends_on:
      - server1
      - server2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"

  libsql-server:
    image: raulvc/rinha-libsql-server:latest
    hostname: db
    networks:
      - rinha
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "390MB"

  etcd:
    image: bitnami/etcd:latest
    hostname: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    networks:
      - rinha
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  server1: &server
    image: raulvc/rinha-app:latest
    hostname: server1
    environment:
      - RUST_ENV=docker
    networks:
      - rinha
    depends_on:
      - libsql-server
      - etcd
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  server2:
    <<: *server
    hostname: server2

networks:
  rinha:
    driver: bridge