version: '3.7'

services:
  redis:
    image: redis:alpine
    hostname: redis
    networks:
      - rinha
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "90MB"

  haproxy:
    image: haproxy:alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:80"
    restart: unless-stopped
    networks:
      - rinha
    depends_on:
      - server1
      - server2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "90MB"

  libsql-server:
    image: raulvc/rinha-libsql-server:latest
    hostname: db
    networks:
      - rinha
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "160MB"

  server1: &server
    image: raulvc/rinha-app:latest
    hostname: server1
    environment:
      - RUST_ENV=docker
    networks:
      - rinha
    restart: unless-stopped
    depends_on:
      - redis
      - libsql-server
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "80MB"

  server2:
    <<: *server
    hostname: server2

networks:
  rinha:
    driver: bridge